spring:
  application:
    name: gateway-test
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: order-service
              uri: http://localhost:${wiremock.server.port} #  WireMock 가짜 서버 주소 연결
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - JwtAuthenticationFilter

jwt:
  secret:
    key: your-256-bit-secret-key-for-logistics-system-jwt-authentication-must-be-long

eureka:
  client:
    enabled: false # 테스트 실행 시 Eureka 클라이언트 비활성화