spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/slack-messages/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/auth/**
                - Path=/api/v1/users/**
                - Path=/api/v1/delivery-managers/**

            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/api/v1/deliveries/**

            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/api/v1/companies/**
                - Path=/api/v1/products/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

            - id: hubs-service
              uri: lb://hubs-service
              predicates:
                - Path=/api/v1/hubs/**
                - Path=/api/v1/hub-routes/**
                - Path=/api/v1/hub-inventories/**

server:
  port: 18080

jwt:
  secret:
    key: your-256-bit-secret-key-for-logistics-system-jwt-authentication-must-be-long

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/