spring:
  application:
    name: gateway-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  config:
    import: "configserver:http://logistics-config-server"
    # 이름과 프로필 참조해 gateway-server.yml, gateway-server-local.yml 등을 로드

server:
  port: 18080


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}