spring:
  application:
    name: gateway-server
  config:
    import: "configserver:"
    # 이름과 프로필 참조해 gateway-server.yml, gateway-server-local.yml 등을 로드
  main:
    web-application-type: reactive

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
                - Path=/api/v1/delivery-managers/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/slack-messages/**
              filters:
                - JwtAuthenticationFilter

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
              filters:
                - JwtAuthenticationFilter

            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/api/v1/deliveries/**
              filters:
                - JwtAuthenticationFilter

            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/api/v1/companies/**
                - Path=/api/v1/products/**
              filters:
                - JwtAuthenticationFilter

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - JwtAuthenticationFilter

            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/api/v1/hubs/**
                - Path=/api/v1/hub-routes/**
                - Path=/api/v1/hub-inventories/**
              filters:
                - JwtAuthenticationFilter
            # Eureka 대시보드 UI 화면 및 정적 리소스 라우팅
            - id: eureka-server-ui
              uri: ${EUREKA_SERVER_URL:http://localhost:8761} # 또는 Eureka 컨테이너 이름 (http://eureka-server:8761)
              predicates:
                - Path=/eureka/ui/**, /eureka/css/**, /eureka/js/**, /eureka/images/**, /eureka/fonts/**
              filters:
                # /eureka/ui 로 들어오면 Eureka Server의 기본 대시보드 경로인 / 로 리라이트
                - RewritePath=/eureka/ui(?<segment>/?.*), /$\{segment}

            # Eureka 화면 내에서 상태 확인 등을 위해 호출되는 API 경로 라우팅
            - id: eureka-server-api
              uri: ${EUREKA_SERVER_URL:http://localhost:8761}
              predicates:
                - Path=/eureka/apps/**, /eureka/instances/**
            # Zipkin 대시보드 UI 및 정적 리소스 / API 라우팅
            - id: zipkin-ui
              uri: ${ZIPKIN_SERVER_URL:http://localhost:9411} # 또는 Docker 컨테이너명 (http://zipkin:9411)
              predicates:
                - Path=/zipkin/**, /zipkin/ui/**, /api/v2/**
              filters:
                # /zipkin 혹은 /zipkin/ui 로 들어오는 요청을 Zipkin 내부 경로로 연결
                - RewritePath=/zipkin(?<segment>/?.*), /zipkin$\{segment}
server:
  port: 18080


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

jwt:
  secret:
    key: ${JWT_SECRET_KEY:your-256-bit-secret-key-for-logistics-system-jwt-authentication-must-be-long}