spring:
  application:
    name: gateway-server
  config:
    import: "configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

server:
  port: 18080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
